version: "3.7"
services:
  web:
    image: frontend_challenge:dev
    container_name: frontend_challenge
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    ports:
      - 3000:80
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}